/**
 * Demo data for instant demos without API calls.
 * GREEN, YELLOW, and RED classification samples.
 */

export const DEMO_DATA: Record<string, any> = {
  green: {
    classification: 'green',
    level: 'GREEN',
    summary: 'Standard Approval',
    document: 'Standard-NDA.txt',
    parties: 'Consello LLC ↔ Acme Corporation',
    type: 'Mutual NDA',
    term: '2 years with 3-year survival',
    governingLaw: 'New York',
    screening: [
      { criterion: 'Mutual Obligations', status: 'pass', note: 'Both parties bound equally' },
      { criterion: 'Term Length', status: 'pass', note: '2 years - within standard range' },
      { criterion: 'Survival Period', status: 'pass', note: '3 years - appropriate' },
      { criterion: 'Public Info Carveout', status: 'pass', note: 'Present and complete' },
      { criterion: 'Prior Possession', status: 'pass', note: 'Properly addressed' },
      { criterion: 'Independent Development', status: 'pass', note: 'Carveout included' },
      { criterion: 'Legal Compulsion', status: 'pass', note: 'Notice requirement included' },
      { criterion: 'Third-Party Receipt', status: 'pass', note: 'Standard carveout present' },
      { criterion: 'Non-Compete Clause', status: 'pass', note: 'None present' },
      { criterion: 'Non-Solicitation', status: 'pass', note: 'None present' },
      { criterion: 'Governing Law', status: 'pass', note: 'New York - preferred jurisdiction' },
      { criterion: 'Remedies', status: 'pass', note: 'Standard injunctive relief' },
    ],
    issues: [],
    recommendation: 'This NDA meets all playbook standards and can be approved via delegation of authority. No escalation required.',
    nextSteps: [
      'Approve NDA via standard delegation',
      'Execute via DocuSign with standard signature blocks',
      'File in contract management system',
      'Set calendar reminder for 2-year expiration',
    ],
  },
  yellow: {
    classification: 'yellow',
    level: 'YELLOW',
    summary: 'Counsel Review Needed',
    document: 'Vendor-NDA-Draft.docx',
    parties: 'Consello LLC ↔ TechVendor Inc.',
    type: 'Mutual NDA',
    term: '3 years with 5-year survival',
    governingLaw: 'California',
    screening: [
      { criterion: 'Mutual Obligations', status: 'pass', note: 'Both parties bound equally' },
      { criterion: 'Term Length', status: 'flag', note: '3 years - at upper limit' },
      { criterion: 'Survival Period', status: 'flag', note: '5 years - above standard' },
      { criterion: 'Public Info Carveout', status: 'pass', note: 'Present and complete' },
      { criterion: 'Prior Possession', status: 'pass', note: 'Properly addressed' },
      { criterion: 'Independent Development', status: 'pass', note: 'Carveout included' },
      { criterion: 'Legal Compulsion', status: 'pass', note: 'Notice requirement included' },
      { criterion: 'Third-Party Receipt', status: 'pass', note: 'Standard carveout present' },
      { criterion: 'Non-Compete Clause', status: 'pass', note: 'None present' },
      { criterion: 'Non-Solicitation', status: 'pass', note: 'None present' },
      { criterion: 'Governing Law', status: 'flag', note: 'California - acceptable but not preferred' },
      { criterion: 'Remedies', status: 'pass', note: 'Standard injunctive relief' },
    ],
    issues: [
      {
        id: 'issue-1',
        severity: 'yellow',
        title: 'Extended Survival Period',
        description: '5-year survival period exceeds our standard 3-year position.',
        risk: 'Longer ongoing obligations post-termination.',
        recommendation: 'Request reduction to 3 years. If pushed back, 4 years is acceptable for strategic vendors.',
        sourceBlockIds: [],
        sourceQuote: '',
      },
      {
        id: 'issue-2',
        severity: 'yellow',
        title: 'California Governing Law',
        description: 'California governing law rather than preferred New York.',
        risk: 'Potentially broader interpretation of confidentiality obligations.',
        recommendation: 'Accept if vendor insists - California is within acceptable jurisdictions per playbook.',
        sourceBlockIds: [],
        sourceQuote: '',
      },
    ],
    recommendation: 'This NDA has minor deviations that should be reviewed by designated counsel before execution. Issues are negotiable and within acceptable ranges.',
    nextSteps: [
      'Route to designated reviewer for approval',
      'Consider negotiating survival period to 3-4 years',
      'Document business justification if accepting California law',
      'Expected turnaround: 1-2 business days',
    ],
  },
  red: {
    classification: 'red',
    level: 'RED',
    summary: 'Escalation Required - Significant Issues',
    document: 'problematic-nda.txt',
    parties: 'Consello LLC (Receiving Party) ← Aggressive Corp (Disclosing Party)',
    type: 'Unilateral NDA (receiving party only)',
    term: 'Perpetual (no expiration)',
    governingLaw: 'Texas (Houston arbitration)',
    screening: [
      { criterion: 'Mutual Obligations', status: 'fail', note: 'Unilateral - we are bound, they are not' },
      { criterion: 'Term Length', status: 'fail', note: 'Perpetual - no defined end date' },
      { criterion: 'Survival Period', status: 'fail', note: 'Perpetual confidentiality obligations' },
      { criterion: 'Public Info Carveout', status: 'pass', note: 'Present' },
      { criterion: 'Prior Possession', status: 'pass', note: 'Present' },
      { criterion: 'Independent Development', status: 'fail', note: 'MISSING - critical carveout absent' },
      { criterion: 'Legal Compulsion', status: 'pass', note: 'Present with notice requirement' },
      { criterion: 'Third-Party Receipt', status: 'pass', note: 'Present' },
      { criterion: 'Non-Compete Clause', status: 'fail', note: '2-year non-compete in their sector' },
      { criterion: 'Non-Solicitation', status: 'fail', note: '3-year employee non-solicitation' },
      { criterion: 'Governing Law', status: 'fail', note: 'Texas with mandatory Houston arbitration' },
      { criterion: 'Remedies', status: 'fail', note: '$500,000 liquidated damages clause' },
    ],
    issues: [
      {
        id: 'issue-1',
        severity: 'red',
        title: 'Unilateral Structure',
        description: 'NDA only binds Consello as receiving party. Counterparty has no confidentiality obligations.',
        risk: 'We cannot share any information requiring protection. Completely one-sided.',
        recommendation: 'Require conversion to mutual NDA or reject.',
        sourceBlockIds: [],
        sourceQuote: 'The Receiving Party agrees to hold in confidence all Confidential Information',
        editPlans: [
          {
            variant: 'preferred' as const,
            description: 'Convert to mutual confidentiality obligations',
            operations: [
              {
                id: 'edit-1a',
                type: 'replace_range' as const,
                blockId: 'demo-block-1',
                startChar: 0,
                endChar: 45,
                newText: 'Each Party (as "Receiving Party") agrees to hold in confidence all Confidential Information disclosed by the other Party (as "Disclosing Party")',
                comment: 'Converted to mutual NDA structure per Consello playbook',
                issueId: 'issue-1',
              },
            ],
          },
        ],
      },
      {
        id: 'issue-2',
        severity: 'red',
        title: 'Missing Independent Development Carveout',
        description: 'No protection for independently developed information or ideas.',
        risk: 'Exposure to claims that our internal work infringes their confidential information.',
        recommendation: 'MUST ADD standard independent development carveout. Non-negotiable.',
        sourceBlockIds: [],
        sourceQuote: '',
        editPlans: [
          {
            variant: 'preferred' as const,
            description: 'Add standard independent development carveout to exclusions',
            operations: [
              {
                id: 'edit-2a',
                type: 'insert_after' as const,
                blockId: 'demo-block-2',
                newText: '(e) information that is independently developed by the Receiving Party without reference to or use of the Disclosing Party\'s Confidential Information, as demonstrated by written records;',
                comment: 'Added required independent development carveout per Consello playbook',
                issueId: 'issue-2',
              },
            ],
          },
        ],
      },
      {
        id: 'issue-3',
        severity: 'red',
        title: 'Non-Compete Clause (2 years)',
        description: 'Section 8.1 prohibits competing in their sector for 2 years after termination.',
        risk: 'Could prevent legitimate business activities and client relationships.',
        recommendation: 'DELETE ENTIRELY. Non-competes are prohibited in NDAs per playbook.',
        sourceBlockIds: [],
        sourceQuote: 'Receiving Party shall not, for a period of two (2) years, directly or indirectly compete',
        editPlans: [
          {
            variant: 'preferred' as const,
            description: 'Delete non-compete clause entirely — prohibited per playbook',
            operations: [
              {
                id: 'edit-3a',
                type: 'delete_range' as const,
                blockId: 'demo-block-3',
                startChar: 0,
                endChar: 200,
                comment: 'Non-compete clauses are prohibited in NDAs per Consello playbook',
                issueId: 'issue-3',
              },
            ],
          },
        ],
      },
    ],
    recommendation: 'DO NOT SIGN. This NDA contains multiple provisions that violate playbook standards and create unacceptable risk. Escalate to senior counsel and provide counterparty with our standard mutual NDA template.',
    nextSteps: [
      'ESCALATE to senior counsel immediately',
      'Prepare detailed counterproposal using Consello standard NDA',
      'Document all issues in contract tracker',
      'Schedule call with counterparty to discuss concerns',
      'Consider whether business relationship justifies negotiation effort',
    ],
  },
};
