/**
 * Demo data for instant demos without API calls.
 * GREEN, YELLOW, and RED classification samples.
 */

// Minimal ParsedDocument shapes so the demo redline export uses the full tracked-changes path
export const DEMO_PARSED_DOCUMENTS: Record<string, any> = {
  yellow: {
    filename: 'Vendor-NDA-Draft.docx',
    fullText: 'The obligations of confidentiality shall survive for a period of five (5) years from the date of disclosure.\n\nThis Agreement shall be governed by and construed in accordance with the laws of the State of California.',
    annotatedText: '[BLOCK:demo-yellow-block-1]The obligations of confidentiality shall survive for a period of five (5) years from the date of disclosure.[/BLOCK]\n\n[BLOCK:demo-yellow-block-2]This Agreement shall be governed by and construed in accordance with the laws of the State of California.[/BLOCK]',
    blocks: [
      {
        id: 'demo-yellow-block-1',
        type: 'paragraph',
        content: 'The obligations of confidentiality shall survive for a period of five (5) years from the date of disclosure.',
        charStart: 0,
        charEnd: 108,
      },
      {
        id: 'demo-yellow-block-2',
        type: 'paragraph',
        content: 'This Agreement shall be governed by and construed in accordance with the laws of the State of California.',
        charStart: 110,
        charEnd: 215,
      },
    ],
    metadata: { pageCount: 3, wordCount: 1200, blockCount: 2 },
  },
  red: {
    filename: 'problematic-nda.txt',
    fullText: 'The Receiving Party agrees to hold in confidence all Confidential Information disclosed by the Disclosing Party.\n\nConfidential Information shall not include information that: (a) is publicly available; (b) was known prior to disclosure; (c) is received from a third party; (d) is required by law to be disclosed.\n\nReceiving Party shall not, for a period of two (2) years following termination, directly or indirectly compete with or solicit employees, clients, or business opportunities from the Disclosing Party in any market or sector.',
    annotatedText: '[BLOCK:demo-block-1]The Receiving Party agrees to hold in confidence all Confidential Information disclosed by the Disclosing Party.[/BLOCK]\n\n[BLOCK:demo-block-2]Confidential Information shall not include information that: (a) is publicly available; (b) was known prior to disclosure; (c) is received from a third party; (d) is required by law to be disclosed.[/BLOCK]\n\n[BLOCK:demo-block-3]Receiving Party shall not, for a period of two (2) years following termination, directly or indirectly compete with or solicit employees, clients, or business opportunities from the Disclosing Party in any market or sector.[/BLOCK]',
    blocks: [
      {
        id: 'demo-block-1',
        type: 'paragraph',
        content: 'The Receiving Party agrees to hold in confidence all Confidential Information disclosed by the Disclosing Party.',
        charStart: 0,
        charEnd: 112,
      },
      {
        id: 'demo-block-2',
        type: 'paragraph',
        content: 'Confidential Information shall not include information that: (a) is publicly available; (b) was known prior to disclosure; (c) is received from a third party; (d) is required by law to be disclosed.',
        charStart: 114,
        charEnd: 312,
      },
      {
        id: 'demo-block-3',
        type: 'paragraph',
        content: 'Receiving Party shall not, for a period of two (2) years following termination, directly or indirectly compete with or solicit employees, clients, or business opportunities from the Disclosing Party in any market or sector.',
        charStart: 314,
        charEnd: 537,
      },
    ],
    metadata: { pageCount: 5, wordCount: 2400, blockCount: 3 },
  },
};

export const DEMO_DATA: Record<string, any> = {
  green: {
    classification: 'green',
    level: 'GREEN',
    summary: 'Standard Approval',
    document: 'Standard-NDA.txt',
    parties: 'Consello LLC ↔ Acme Corporation',
    type: 'Mutual NDA',
    term: '2 years with 3-year survival',
    governingLaw: 'New York',
    screening: [
      { criterion: 'Mutual Obligations', status: 'pass', note: 'Both parties bound equally' },
      { criterion: 'Term Length', status: 'pass', note: '2 years - within standard range' },
      { criterion: 'Survival Period', status: 'pass', note: '3 years - appropriate' },
      { criterion: 'Public Info Carveout', status: 'pass', note: 'Present and complete' },
      { criterion: 'Prior Possession', status: 'pass', note: 'Properly addressed' },
      { criterion: 'Independent Development', status: 'pass', note: 'Carveout included' },
      { criterion: 'Legal Compulsion', status: 'pass', note: 'Notice requirement included' },
      { criterion: 'Third-Party Receipt', status: 'pass', note: 'Standard carveout present' },
      { criterion: 'Non-Compete Clause', status: 'pass', note: 'None present' },
      { criterion: 'Non-Solicitation', status: 'pass', note: 'None present' },
      { criterion: 'Governing Law', status: 'pass', note: 'New York - preferred jurisdiction' },
      { criterion: 'Remedies', status: 'pass', note: 'Standard injunctive relief' },
    ],
    issues: [],
    recommendation: 'This NDA meets all playbook standards and can be approved via delegation of authority. No escalation required.',
    nextSteps: [
      'Approve NDA via standard delegation',
      'Execute via DocuSign with standard signature blocks',
      'File in contract management system',
      'Set calendar reminder for 2-year expiration',
    ],
  },
  yellow: {
    classification: 'yellow',
    level: 'YELLOW',
    summary: 'Counsel Review Needed',
    document: 'Vendor-NDA-Draft.docx',
    parties: 'Consello LLC ↔ TechVendor Inc.',
    type: 'Mutual NDA',
    term: '3 years with 5-year survival',
    governingLaw: 'California',
    screening: [
      { criterion: 'Mutual Obligations', status: 'pass', note: 'Both parties bound equally' },
      { criterion: 'Term Length', status: 'flag', note: '3 years - at upper limit' },
      { criterion: 'Survival Period', status: 'flag', note: '5 years - above standard' },
      { criterion: 'Public Info Carveout', status: 'pass', note: 'Present and complete' },
      { criterion: 'Prior Possession', status: 'pass', note: 'Properly addressed' },
      { criterion: 'Independent Development', status: 'pass', note: 'Carveout included' },
      { criterion: 'Legal Compulsion', status: 'pass', note: 'Notice requirement included' },
      { criterion: 'Third-Party Receipt', status: 'pass', note: 'Standard carveout present' },
      { criterion: 'Non-Compete Clause', status: 'pass', note: 'None present' },
      { criterion: 'Non-Solicitation', status: 'pass', note: 'None present' },
      { criterion: 'Governing Law', status: 'flag', note: 'California - acceptable but not preferred' },
      { criterion: 'Remedies', status: 'pass', note: 'Standard injunctive relief' },
    ],
    issues: [
      {
        id: 'issue-1',
        severity: 'yellow',
        title: 'Extended Survival Period',
        description: '5-year survival period exceeds our standard 3-year position.',
        risk: 'Longer ongoing obligations post-termination.',
        recommendation: 'Request reduction to 3 years. If pushed back, 4 years is acceptable for strategic vendors.',
        sourceBlockIds: ['demo-yellow-block-1'],
        sourceQuote: 'The obligations of confidentiality shall survive for a period of five (5) years',
        editPlans: [
          {
            variant: 'preferred' as const,
            description: 'Reduce survival period to standard 3 years',
            operations: [
              {
                id: 'edit-y1a',
                type: 'replace_range' as const,
                blockId: 'demo-yellow-block-1',
                startChar: 0,
                endChar: 108,
                newText: 'The obligations of confidentiality shall survive for a period of three (3) years from the date of disclosure.',
                comment: 'Reduced survival period from 5 to 3 years per Consello playbook standard',
                issueId: 'issue-1',
              },
            ],
          },
          {
            variant: 'fallback' as const,
            description: 'Compromise at 4 years for strategic vendor',
            operations: [
              {
                id: 'edit-y1b',
                type: 'replace_range' as const,
                blockId: 'demo-yellow-block-1',
                startChar: 0,
                endChar: 108,
                newText: 'The obligations of confidentiality shall survive for a period of four (4) years from the date of disclosure.',
                comment: 'Reduced survival period from 5 to 4 years — acceptable range for strategic vendors',
                issueId: 'issue-1',
              },
            ],
          },
        ],
        diffSegments: {
          preferred: [
            { type: 'unchanged' as const, text: 'The obligations of confidentiality shall survive for a period of ' },
            { type: 'delete' as const, text: 'five (5)' },
            { type: 'insert' as const, text: 'three (3)' },
            { type: 'unchanged' as const, text: ' years from the date of disclosure.' },
          ],
          fallback: [
            { type: 'unchanged' as const, text: 'The obligations of confidentiality shall survive for a period of ' },
            { type: 'delete' as const, text: 'five (5)' },
            { type: 'insert' as const, text: 'four (4)' },
            { type: 'unchanged' as const, text: ' years from the date of disclosure.' },
          ],
        },
      },
      {
        id: 'issue-2',
        severity: 'yellow',
        title: 'California Governing Law',
        description: 'California governing law rather than preferred New York.',
        risk: 'Potentially broader interpretation of confidentiality obligations.',
        recommendation: 'Accept if vendor insists - California is within acceptable jurisdictions per playbook.',
        sourceBlockIds: ['demo-yellow-block-2'],
        sourceQuote: 'This Agreement shall be governed by and construed in accordance with the laws of the State of California',
        editPlans: [
          {
            variant: 'preferred' as const,
            description: 'Change governing law to New York',
            operations: [
              {
                id: 'edit-y2a',
                type: 'replace_range' as const,
                blockId: 'demo-yellow-block-2',
                startChar: 0,
                endChar: 105,
                newText: 'This Agreement shall be governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of laws principles',
                comment: 'Changed governing law from California to preferred New York jurisdiction per playbook',
                issueId: 'issue-2',
              },
            ],
          },
        ],
        diffSegments: {
          preferred: [
            { type: 'unchanged' as const, text: 'This Agreement shall be governed by and construed in accordance with the laws of the State of ' },
            { type: 'delete' as const, text: 'California' },
            { type: 'insert' as const, text: 'New York, without regard to its conflict of laws principles' },
            { type: 'unchanged' as const, text: '.' },
          ],
        },
      },
    ],
    recommendation: 'This NDA has minor deviations that should be reviewed by designated counsel before execution. Issues are negotiable and within acceptable ranges.',
    nextSteps: [
      'Route to designated reviewer for approval',
      'Consider negotiating survival period to 3-4 years',
      'Document business justification if accepting California law',
      'Expected turnaround: 1-2 business days',
    ],
  },
  red: {
    classification: 'red',
    level: 'RED',
    summary: 'Escalation Required - Significant Issues',
    document: 'problematic-nda.txt',
    parties: 'Consello LLC (Receiving Party) ← Aggressive Corp (Disclosing Party)',
    type: 'Unilateral NDA (receiving party only)',
    term: 'Perpetual (no expiration)',
    governingLaw: 'Texas (Houston arbitration)',
    screening: [
      { criterion: 'Mutual Obligations', status: 'fail', note: 'Unilateral - we are bound, they are not' },
      { criterion: 'Term Length', status: 'fail', note: 'Perpetual - no defined end date' },
      { criterion: 'Survival Period', status: 'fail', note: 'Perpetual confidentiality obligations' },
      { criterion: 'Public Info Carveout', status: 'pass', note: 'Present' },
      { criterion: 'Prior Possession', status: 'pass', note: 'Present' },
      { criterion: 'Independent Development', status: 'fail', note: 'MISSING - critical carveout absent' },
      { criterion: 'Legal Compulsion', status: 'pass', note: 'Present with notice requirement' },
      { criterion: 'Third-Party Receipt', status: 'pass', note: 'Present' },
      { criterion: 'Non-Compete Clause', status: 'fail', note: '2-year non-compete in their sector' },
      { criterion: 'Non-Solicitation', status: 'fail', note: '3-year employee non-solicitation' },
      { criterion: 'Governing Law', status: 'fail', note: 'Texas with mandatory Houston arbitration' },
      { criterion: 'Remedies', status: 'fail', note: '$500,000 liquidated damages clause' },
    ],
    issues: [
      {
        id: 'issue-1',
        severity: 'red',
        title: 'Unilateral Structure',
        description: 'NDA only binds Consello as receiving party. Counterparty has no confidentiality obligations.',
        risk: 'We cannot share any information requiring protection. Completely one-sided.',
        recommendation: 'Require conversion to mutual NDA or reject.',
        sourceBlockIds: [],
        sourceQuote: 'The Receiving Party agrees to hold in confidence all Confidential Information',
        editPlans: [
          {
            variant: 'preferred' as const,
            description: 'Convert to mutual confidentiality obligations',
            operations: [
              {
                id: 'edit-1a',
                type: 'replace_range' as const,
                blockId: 'demo-block-1',
                startChar: 0,
                endChar: 112,
                newText: 'Each Party (as "Receiving Party") agrees to hold in confidence all Confidential Information disclosed by the other Party (as "Disclosing Party")',
                comment: 'Converted to mutual NDA structure per Consello playbook',
                issueId: 'issue-1',
              },
            ],
          },
        ],
        diffSegments: {
          preferred: [
            { type: 'delete' as const, text: 'The Receiving Party' },
            { type: 'insert' as const, text: 'Each Party (as "Receiving Party")' },
            { type: 'unchanged' as const, text: ' agrees to hold in confidence all Confidential Information disclosed by ' },
            { type: 'delete' as const, text: 'the Disclosing Party' },
            { type: 'insert' as const, text: 'the other Party (as "Disclosing Party")' },
            { type: 'unchanged' as const, text: '.' },
          ],
        },
      },
      {
        id: 'issue-2',
        severity: 'red',
        title: 'Missing Independent Development Carveout',
        description: 'No protection for independently developed information or ideas.',
        risk: 'Exposure to claims that our internal work infringes their confidential information.',
        recommendation: 'MUST ADD standard independent development carveout. Non-negotiable.',
        sourceBlockIds: [],
        sourceQuote: '',
        editPlans: [
          {
            variant: 'preferred' as const,
            description: 'Add standard independent development carveout to exclusions',
            operations: [
              {
                id: 'edit-2a',
                type: 'insert_after' as const,
                blockId: 'demo-block-2',
                newText: '(e) information that is independently developed by the Receiving Party without reference to or use of the Disclosing Party\'s Confidential Information, as demonstrated by written records;',
                comment: 'Added required independent development carveout per Consello playbook',
                issueId: 'issue-2',
              },
            ],
          },
        ],
        diffSegments: {
          preferred: [
            { type: 'unchanged' as const, text: '(d) is required by law to be disclosed. ' },
            { type: 'insert' as const, text: '(e) information that is independently developed by the Receiving Party without reference to or use of the Disclosing Party\'s Confidential Information, as demonstrated by written records;' },
          ],
        },
      },
      {
        id: 'issue-3',
        severity: 'red',
        title: 'Non-Compete Clause (2 years)',
        description: 'Section 8.1 prohibits competing in their sector for 2 years after termination.',
        risk: 'Could prevent legitimate business activities and client relationships.',
        recommendation: 'DELETE ENTIRELY. Non-competes are prohibited in NDAs per playbook.',
        sourceBlockIds: [],
        sourceQuote: 'Receiving Party shall not, for a period of two (2) years, directly or indirectly compete',
        editPlans: [
          {
            variant: 'preferred' as const,
            description: 'Delete non-compete clause entirely — prohibited per playbook',
            operations: [
              {
                id: 'edit-3a',
                type: 'delete_range' as const,
                blockId: 'demo-block-3',
                startChar: 0,
                endChar: 223,
                comment: 'Non-compete clauses are prohibited in NDAs per Consello playbook',
                issueId: 'issue-3',
              },
            ],
          },
        ],
        diffSegments: {
          preferred: [
            { type: 'delete' as const, text: 'Receiving Party shall not, for a period of two (2) years following termination, directly or indirectly compete with or solicit employees, clients, or business opportunities from the Disclosing Party in any market or sector.' },
          ],
        },
      },
    ],
    recommendation: 'DO NOT SIGN. This NDA contains multiple provisions that violate playbook standards and create unacceptable risk. Escalate to senior counsel and provide counterparty with our standard mutual NDA template.',
    nextSteps: [
      'ESCALATE to senior counsel immediately',
      'Prepare detailed counterproposal using Consello standard NDA',
      'Document all issues in contract tracker',
      'Schedule call with counterparty to discuss concerns',
      'Consider whether business relationship justifies negotiation effort',
    ],
  },
};
